### ISSUE TITLE
LIB 速度统计

### ISSUE THREAD

**Issue by qianxiaofeng** [eosiosg/dpos-pbft#2]
统计结果这里留一个记录吧

**Comment by oldcold** [comment]
无压力情况下的统计：https://docs.google.com/spreadsheets/d/1YaQL-UpyPCAnc_4O4JVkldkJQivzXM2ywCZzORSmwnw/edit?usp=sharing

**Comment by oldcold** [comment]
TPS=300情况下的统计：https://docs.google.com/spreadsheets/d/1yr9GVcHMSaKjX7_D3Keg0XBE_mLuOCWtYNTbQ5JSXHY/edit#gid=537319685
